source/accounts/urls.py
from django.urls import path
from accounts.views import logout_view, login_view, register_view, \
    user_activate_view, UserDetailView, UserChangeView, UserChangePasswordView, UsersListView, password_reset_email_view, PasswordResetFormView

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users/', UsersListView.as_view(), name='users_list'),
    path('reset-password/', password_reset_email_view, name='password_reset_email'),
    path('reset-password/<token>/', PasswordResetFormView.as_view(), name='password_reset_form')
]


app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import ProductsView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ReviewsView, ReviewCreateView, ReviewUpdateView, ReviewDeleteView

urlpatterns = [
    path('', ProductsView.as_view(), name='products_view'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_add'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('reviews/', ReviewsView.as_view(), name='reviews_view'),
    path('review/add-product/<int:pk>/', ReviewCreateView.as_view(), name='review_add'),
    path('product/<int:pk>/update-review/', ReviewUpdateView.as_view(), name='review_update'),
    path('product/<int:pk>/delete-review/', ReviewDeleteView.as_view(), name='review_delete'),

]

app_name = 'webapp'

source/webapp/models.py
from django.conf import settings
from django.db import models

CATEGORY_CHOICES = (
    ('other', 'Другое'),
    ('food', 'Еда'),
    ('clothes', 'Одежда'),
    ('household', 'Товары для дома'),
)



class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Товар', null=False, blank=False)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория', null=False, blank=False)
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание')
    photo = models.ImageField(upload_to='user_pics', null=True, blank=True, verbose_name='Фото')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


RAITING_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Author', related_name='reviews')
    product = models.ForeignKey(Product, related_name='product_order', max_length=100, on_delete=models.CASCADE)
    order_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание отзыва')
    rating = models.CharField(max_length=50, choices=RAITING_CHOICES, default=None,
                                verbose_name='Рейтинг', null=False, blank=False)

    def __str__(self):
        return str(self.author)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms


from webapp.models import Product, Review, RAITING_CHOICES


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'photo']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['order_description', 'rating']

source/webapp/views/product_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class ProductsView(ListView):
    template_name = 'product/list.html'
    model = Product
    context_key = 'products'


class ProductView(DetailView):
    template_name = 'product/product.html'
    context_object_name = 'product'
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'product/create.html'
    form_class = ProductForm
    permission_required = 'webapp.add_product'
    permission_denied_message = '403 Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    template_name = 'product/update.html'
    form_class = ProductForm
    context_object_name = 'product'
    permission_required = 'webapp.change_product'
    permission_denied_message = '403 Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    pk_kwargs_url = 'pk'
    template_name = 'product/delete.html'
    context_object_name = 'product'
    success_url = reverse_lazy('webapp:products_view')
    permission_required = 'webapp.delete_product'
    permission_denied_message = '403 Доступ запрещен'


    # def get_success_url(self):
    #     return reverse('webapp:product_view', kwargs={'pk': self.object.pk})

source/webapp/views/review_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, FormView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewsView(ListView):
    context_object_name = 'reviews'
    model = Review


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/create.html'
    form_class = ReviewForm

    def get_queryset(self):
        product = get_object_or_404(Product, name=self.kwargs['pk'])
        return Review.objects.filter(product=product)

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.product = product
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/update.html'
    form_class = ReviewForm
    context_object_name = 'review'
    permission_required = 'webapp.change_review'
    permission_denied_message = '403 Доступ запрещен'

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.product = product
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    pk_kwargs_url = 'pk'
    template_name = 'review/delete.html'
    context_object_name = 'review'
    success_url = reverse_lazy('webapp:products_view')
    permission_required = 'webapp.delete_review'
    permission_denied_message = '403 Доступ запрещен'

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MySite{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
                <li><a href="{% url 'webapp:products_view' %}">Home</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:users_list' %}">Users</a></li>
                    {% if perms.webapp.add_product %}
                        <a href="{% url 'webapp:product_add' %}">Add product</a>
                     {% endif %}
                {% endif %}
                <li class="menu-right">
                    {% if request.user.is_authenticated %}
                        <li>Hello,<a href="{% url 'accounts:user_detail' request.user.pk %}">
                                {{ user }}!</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Log OUT</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Log IN</a></li>
                        <li><a href="{% url 'accounts:register' %}">Sign UP</a></li>
                    {% endif %}
                </li>
                {% block menu %}{% endblock %}
            </ul>
        </div>
    </nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>