source/accounts/urls.py
from django.urls import path
from accounts.views import logout_view, login_view, register_view, \
    user_activate_view, UserDetailView, UserChangeView, UserChangePasswordView, UsersListView, password_reset_email_view, PasswordResetFormView

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users/', UsersListView.as_view(), name='users_list'),
    path('reset-password/', password_reset_email_view, name='password_reset_email'),
    path('reset-password/<token>/', PasswordResetFormView.as_view(), name='password_reset_form')
]


app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import ProductsView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ReviewsView, ReviewCreateView, ReviewUpdateView, ReviewDeleteView

urlpatterns = [
    path('', ProductsView.as_view(), name='products_view'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_add'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('reviews/', ReviewsView.as_view(), name='reviews_view'),
    path('review/add-product/<int:pk>/', ReviewCreateView.as_view(), name='review_add'),
    path('product/<int:pk>/update-review/', ReviewUpdateView.as_view(), name='review_update'),
    path('product/<int:pk>/delete-review/', ReviewDeleteView.as_view(), name='review_delete'),

]

app_name = 'webapp'

source/webapp/models.py
from django.conf import settings
from django.db import models

CATEGORY_CHOICES = (
    ('other', 'Другое'),
    ('food', 'Еда'),
    ('clothes', 'Одежда'),
    ('household', 'Товары для дома'),
)



class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Товар', null=False, blank=False)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория', null=False, blank=False)
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание')
    photo = models.ImageField(upload_to='user_pics', null=True, blank=True, verbose_name='Фото')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


RAITING_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Author', related_name='reviews')
    product = models.ForeignKey(Product, related_name='product_order', max_length=100, on_delete=models.CASCADE)
    order_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание отзыва')
    rating = models.CharField(max_length=50, choices=RAITING_CHOICES, default=None,
                                verbose_name='Рейтинг', null=False, blank=False)

    def __str__(self):
        return str(self.author)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms


from webapp.models import Product, Review, RAITING_CHOICES


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'photo']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['order_description', 'rating']

source/webapp/views/product_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class ProductsView(ListView):
    template_name = 'product/list.html'
    model = Product
    context_key = 'products'


class ProductView(DetailView):
    template_name = 'product/product.html'
    context_object_name = 'product'
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'product/create.html'
    form_class = ProductForm
    permission_required = 'webapp.add_product'
    permission_denied_message = '403 Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    template_name = 'product/update.html'
    form_class = ProductForm
    context_object_name = 'product'
    permission_required = 'webapp.change_product'
    permission_denied_message = '403 Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    pk_kwargs_url = 'pk'
    template_name = 'product/delete.html'
    context_object_name = 'product'
    success_url = reverse_lazy('webapp:products_view')
    permission_required = 'webapp.delete_product'
    permission_denied_message = '403 Доступ запрещен'


    # def get_success_url(self):
    #     return reverse('webapp:product_view', kwargs={'pk': self.object.pk})

source/webapp/views/review_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, FormView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewsView(ListView):
    context_object_name = 'reviews'
    model = Review


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/create.html'
    form_class = ReviewForm

    def get_queryset(self):
        product = get_object_or_404(Product, name=self.kwargs['pk'])
        return Review.objects.filter(product=product)

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.product = product
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/update.html'
    form_class = ReviewForm
    context_object_name = 'review'
    permission_required = 'webapp.change_review'
    permission_denied_message = '403 Доступ запрещен'

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.product = product
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    pk_kwargs_url = 'pk'
    template_name = 'review/delete.html'
    context_object_name = 'review'
    success_url = reverse_lazy('webapp:products_view')
    permission_required = 'webapp.delete_review'
    permission_denied_message = '403 Доступ запрещен'

source/webapp/templates/product/create.html
{% extends 'base.html' %}
{% block title %}Create product{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:products_view' %}">Products</a></li>
{% endblock %}
{% block content %}
    <h1>Create product</h1>
    <form method="POST" action="{% url 'webapp:product_add' %}">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/product/delete.html
{% extends "base.html" %}
{% block title %}Delete product{% endblock %}
{% block content %}
    <h1>Are you sure want to delete project "{{ product }}"?</h1>
    <form method="POST" action="{% url "webapp:product_delete" product.pk %}" class="text-center" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm" class="btn btn-danger"></p>
        <p><a href="{% url 'webapp:products_view' %}" class="btn btn-default">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/product/list.html
{% extends 'base.html' %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1 class="mt-3">Products</h1>
{#    {% include 'partial/simple_search.html' %}#}
{#    <hr>#}
{#        {% if is_paginated  %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
    <hr/>
    <div class="row">
        {% for product in product_list %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-3">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'webapp:product_view' product.pk %}"><h2 class="card-text card-link">
                            {{ product.name }}
                        </h2></a>

                        {% if perms.webapp.change_product %}
                            <a href="{% url 'webapp:product_update' product.pk %}"><i class="fas fa-edit"></i></a>
                        {% endif %}
                        {% if perms.webapp.delete_product %}
                            <a href="{% url 'webapp:product_delete' product.pk %}"><i class="fas fa-trash"></i></a>
                        {% endif %}
                        <p class="card-text">{{ product.get_category_display }}</p>
                        <p class="card-text text-right"><b>Description: </b>{{ product.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{#          {% if is_paginated  %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
{% endblock %}

source/webapp/templates/product/product.html
{% extends 'base.html' %}
{% block title %}{{ product.name }}{% endblock %}

{% block menu %}
    {% if perms.webapp.change_product %}
        <li><a href="{% url 'webapp:product_update' product.pk %}">Edit</a></li>
    {% endif %}
    {% if perms.webapp.delete_product %}
        <li><a href="{% url 'webapp:product_delete' product.pk %}">Delete</a></li>
    {% endif %}
    {% if perms.webapp.add_product%}
        <li><a href="{% url 'webapp:product_add' %}">Create</a></li>
    {% endif %}
{% endblock %}

{% block content %}

        {% if product.photo %}
        <img class="avatar" src="{{ product.photo.url }}"
             width="200" height="200" alt="user picture">
    {% endif %}
    <h1>{{ product.name }}</h1>
    <p><b>Description: </b>{{ product.description }}</p>
    <p><b>Status: </b>{{ product.category }}</p>

    <a href="{% url 'webapp:review_add' product.pk %}"><i class="fas fa-plus-square"></i></a>

    <h2>Reviews</h2>
    <div class="task-list">
        {% for review in product.product_order.all  %}
            <hr>
            <div class="task">
                <p>Author: <a href="{% url 'accounts:user_detail' review.author.pk %}"><b class="card-text card-link">
                    {{ review.author }}
                </b></a></p>
                <p>Description: <b>{{ review.order_description }}</b></p>
                <p>Email: <b>{{ review.author.email }}</b></p>
                <div class="pre">Rating: {{ review.rating }}</div>
                {% if perms.webapp.change_review %}
                    <a href="{% url 'webapp:review_update' review.pk %}"><i class="fas fa-edit"></i></a>
                {% endif %}
                {% if perms.webapp.delete_review %}
                    <a href="{% url 'webapp:review_delete' review.pk %}"><i class="fas fa-trash"></i></a>
                {% endif %}
            </div>
    {% endfor %}

{% endblock %}

source/webapp/templates/product/update.html
{% extends "base.html" %}
{% block title %}Update product{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:products_view' %}">Products</a></li>
{% endblock %}
{% block content %}
    <h1>Update Product</h1>
    <form method="POST" action="{% url "webapp:product_update" product.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}